export const GET_COSTTYPES = "GET_COSTTYPES";
export const GET_COSTTYPES_DONE = "GET_COSTTYPES_DONE";
export const GET_COSTS = "GET_COSTS";
export const GET_COSTS_DONE = "GET_COSTS_DONE";
export const GET_INCOMES = "GET_INCOMES";
export const GET_INCOMES_DONE = "GET_INCOMES_DONE";

export const GET_FULL_YEAR_INCOMES = "GET_FULL_YEAR_INCOMES";
export const GET_FULL_YEAR_INCOMES_DONE = "GET_FULL_YEAR_INCOMES_DONE";
export const GET_MONTHLY_INCOMES = "GET_MONTHLY_INCOMES";
export const GET_MONTHLY_INCOMES_DONE = "GET_MONTHLY_INCOMES_DONE";
export const GET_CHART_INCOMES = "GET_CHART_INCOMES";
export const GET_CHART_INCOMES_DONE = "GET_CHART_INCOMES_DONE";

export const GET_FULL_YEAR_COSTS = "GET_FULL_YEAR_COSTS";
export const GET_FULL_YEAR_COSTS_DONE = "GET_FULL_YEAR_COSTS_DONE";
export const GET_MONTHLY_COSTS = "GET_MONTHLY_COSTS";
export const GET_MONTHLY_COSTS_DONE = "GET_MONTHLY_COSTS_DONE";
export const GET_CHART_COSTS = "GET_CHART_COSTS";
export const GET_CHART_COSTS_DONE = "GET_CHART_COSTS_DONE";

export const ADD_COST = "ADD_COST";
export const ADD_INCOME = "ADD_INCOME";
export const ADD_COSTTYPE = "ADD_COSTTYPE";
export const ADD_COSTTYPE_DONE = "ADD_COSTTYPE_DONE";

export const DELETE_COST = "DELETE_COST";
export const DELETE_INCOME = "DELETE_INCOME";
export const DELETE_COSTTYPE = "DELETE_COSTTYPE";
export const DELETE_COSTTYPE_DONE = "DELETE_COSTTYPE_DONE";

export const GET_COST_BY_TYPE = "GET_COST_BY_TYPE";
export const GET_COST_BY_TYPE_DONE = "GET_COST_BY_TYPE_DONE";

export const GET_COST_TYPE_CATEGORIES = "GET_COST_TYPE_CATEGORIES";
export const GET_COST_TYPE_CATEGORIES_DONE = "GET_COST_TYPE_CATEGORIES_DONE";